version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gbt-postgres-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gbt_template
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gbt-dev-network

  migrate:
    image: migrate/migrate
    container_name: gbt-migrate-dev
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@postgres:5432/gbt_template?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gbt-dev-network

volumes:
  postgres_dev_data:

networks:
  gbt-dev-network:
    driver: bridge
